# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9de8caca4d84a8589088865abf8d071d339895aba5bf092cd3c5c56c6e3507862aa66fc3fd6c945f2326b54238bc1c8ca7d69f6f6fbe36523b50d9fec90034a9

test:
  secret_key_base: 8daa2afccacffae3209a4ad594a3893236026ff5c2450e8952e86de93b8a40b399d30a1f0c1c2f721173929a780721cf6b8b0c9170e6a939a8262976e34dd09d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
